// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdhhytusycmbhmucugdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kaGh5dHVzeWNtYmhtdWN1Z2RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNzA3NzIsImV4cCI6MjA1Mzc0Njc3Mn0.-rZiKRsndgSbIXwabT0t0C3Lb_umib7PF71aERRkoiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);